# Generated by Django 2.2.10 on 2021-02-04 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_name', models.CharField(max_length=30)),
                ('delivery_city', models.CharField(max_length=30)),
                ('delivery_address', models.CharField(max_length=50)),
                ('delivery_pin_code', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_whatsapp_number', models.CharField(max_length=20)),
                ('billing_name', models.CharField(max_length=30)),
                ('billing_city', models.CharField(max_length=30)),
                ('billing_address', models.CharField(max_length=50)),
                ('billing_pin_code', models.DecimalField(decimal_places=2, max_digits=5)),
                ('billing_whatsapp_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory_name', models.CharField(max_length=30)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_description', models.CharField(max_length=50)),
                ('date_of_addition', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('business_name', models.CharField(max_length=30, unique=True)),
                ('city', models.CharField(max_length=30)),
                ('seller', models.CharField(max_length=1)),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_name', models.CharField(max_length=30)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=10)),
                ('whatsapp_number', models.CharField(max_length=20, unique=True)),
                ('bank_name', models.CharField(max_length=30)),
                ('bank_city', models.CharField(max_length=30)),
                ('ifsc', models.CharField(max_length=10)),
                ('branch_name', models.CharField(max_length=30)),
                ('google_pay_id', models.CharField(max_length=30, unique=True)),
                ('upi_id', models.CharField(max_length=20, unique=True)),
                ('google_pay_number', models.CharField(max_length=20, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('photos', models.ImageField(upload_to='images/')),
                ('gst', models.CharField(max_length=30)),
                ('courier_self', models.CharField(max_length=30)),
                ('self_delivery_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_partner_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('product_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('catagory_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Catagory')),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DeliveryPartner')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_order', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('basic_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=10)),
                ('shipment_date', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.BuyerProfile')),
                ('delivery_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.DeliveryPartner')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.SellerProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_message', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Keyword')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPartnerOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(max_length=10)),
                ('shipment_date', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('group_commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Catagory')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
                ('country_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('catagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Catagory')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Keyword')),
            ],
        ),
        migrations.AddField(
            model_name='buyerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User'),
        ),
        migrations.CreateModel(
            name='Auth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('super_admin', models.CharField(max_length=10)),
                ('group_admin', models.CharField(max_length=10)),
                ('delivery_admin', models.CharField(max_length=10)),
                ('screen_id_1', models.BooleanField(default=False)),
                ('screen_id_2', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
        ),
    ]
